name: Post coverage stats

# Need to run this manually (for example, due to a GitHub outage)?
# XXX example invocation to backfill stats

permissions: {}

on:
  schedule:
    # Thursdays at 12:01 pm. Run times aren't guaranteed, so hopefully this will
    # run before the WebDX CG meeting each week.
    - cron: 01 12 * * 4
      timezone: Etc/UTC
  workflow_dispatch:
    inputs:
      current:
        description: "ref name (i.e., branch, tag, or commit)"
        # required: true
        type: string
      previous:
        description: "ref name (i.e., branch, tag, or commit hash)"
        # required: true
        type: string
      issue_number:
        description: "issue number to comment on"
        # required: true
        type: string

env:
  DEFAULT_ISSUE: 37  # XXX replace this with a real issue number

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  open_pr:
    name: Generate stats and post comment
    runs-on: ubuntu-latest
    permissions:
      issues: write  # to write comments on issues
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          persist-credentials: false
          # Check out the complete history, but not all the blobs
          filter: blob:none
          fetch-depth: 0
      - name: Get default commits
        id: defaults
        if: "${{ github.event.inputs.current == '' }}"
        run: |
          echo "current=$(git rev-list -1 --before="$(date --utc -d '-7 days 12:00:00' '+%Y-%m-%d %T')" main)" >> "$GITHUB_OUTPUT"
          echo "previous=$(git rev-list -1 --before="$(date --utc -d 'today 12:00:00' '+%Y-%m-%d %T')" main)" >> "$GITHUB_OUTPUT"
      - name: Check out previous
        run: git checkout "$PREVIOUS_REF"
        env:
          PREVIOUS_REF: ${{ inputs.previous || steps.defaults.outputs.previous }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - name: Generate stats for previous
        run: |
          npm ci
          previous_result="$(mktemp)"
          npm run --silent stats > "$previous_result"
          echo "previous_result=$previous_result" >> "$GITHUB_ENV"
      - name: Check out current
        run: git checkout "$CURRENT_REF"
        env:
          CURRENT_REF: ${{ inputs.previous || steps.defaults.outputs.current }}
      - name: Generate stats for current
        run: |
          npm ci
          report_markdown="$(mktemp)"
          npm run --silent stats -- --previous="$previous_result" | npx tsx ./scripts/stats-report.ts - > "$report_markdown"
          echo "report_markdown=$report_markdown" >> "$GITHUB_ENV"
      - name: Post comment
        run: gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body-file="$report_markdown"
        env:
          ISSUE_NUMBER: ${{ inputs.issue_number || env.DEFAULT_ISSUE }}
          GH_TOKEN: ${{ github.token }}
